spring.application.name=testing-system

# Dòng này ?ã g?p URL, Port 3307 (ho?c 3306 tùy máy b?n), Database name và Encoding
spring.datasource.url=jdbc:mysql://localhost:3307/BTVN_BUOI4?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=root

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true